- name: Test Ansible setup
  hosts: localhost
  connection: local
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: "Ansible is successfully installed on {{ ansible_hostname }}"

